'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { FormField } from '@/components/ui/form-field';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { showErrorToast, showSuccessToast } from '@/lib/toast-helpers';
import { generateSlug } from '@/lib/utils/slug';

/**
 * Validation schema for the club form.
 * Used for both create and edit modes.
 */
const clubFormSchema = z.object({
  name: z
    .string()
    .min(1, 'Name is required')
    .max(100, 'Name must be at most 100 characters'),
  slug: z
    .string()
    .regex(/^[a-z0-9-]*$/, 'Slug must be lowercase alphanumeric with hyphens')
    .max(50, 'Slug must be at most 50 characters')
    .optional()
    .or(z.literal('')),
  facilityId: z.string().optional(),
});

type ClubFormData = z.infer<typeof clubFormSchema>;

interface Facility {
  id: string;
  name: string;
}

interface ClubFormProps {
  /**
   * Form mode: 'create' for new clubs, 'edit' for existing clubs.
   */
  mode: 'create' | 'edit';
  /**
   * Club ID for edit mode. Required when mode is 'edit'.
   */
  clubId?: string;
  /**
   * Default values to pre-populate the form.
   */
  defaultValues?: Partial<ClubFormData>;
  /**
   * List of facilities for the dropdown (create mode).
   */
  facilities?: Facility[];
  /**
   * Pre-selected facility ID from URL params (create mode).
   */
  preselectedFacilityId?: string;
  /**
   * Current facility name for display (edit mode).
   */
  currentFacilityName?: string;
}

/**
 * Reusable form component for creating and editing clubs.
 *
 * Create mode:
 * - POSTs to /api/admin/clubs
 * - Requires facility selection
 * - Auto-generates slug from name if empty
 *
 * Edit mode:
 * - PATCHes to /api/admin/clubs/[clubId]
 * - Facility field is read-only (use move dialog instead)
 *
 * Uses react-hook-form with zod validation.
 */
export function ClubForm({
  mode,
  clubId,
  defaultValues,
  facilities = [],
  preselectedFacilityId,
  currentFacilityName,
}: ClubFormProps) {
  const router = useRouter();
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);

  const {
    register,
    handleSubmit,
    control,
    setValue,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<ClubFormData>({
    resolver: zodResolver(clubFormSchema),
    defaultValues: {
      name: defaultValues?.name || '',
      slug: defaultValues?.slug || '',
      facilityId: preselectedFacilityId || defaultValues?.facilityId || '',
    },
    mode: 'onTouched',
    reValidateMode: 'onChange',
  });

  const watchedName = watch('name');
  const watchedSlug = watch('slug');

  /**
   * Handle name blur to auto-generate slug in create mode.
   */
  const handleNameBlur = () => {
    if (mode === 'create' && slugAutoGenerated && watchedName && !watchedSlug) {
      const generated = generateSlug(watchedName);
      setValue('slug', generated);
    }
  };

  /**
   * Mark slug as manually edited when user types in it.
   */
  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSlugAutoGenerated(false);
    // Let the register handle the actual value change
  };

  const onSubmit = async (data: ClubFormData) => {
    try {
      const url = mode === 'create'
        ? '/api/admin/clubs'
        : `/api/admin/clubs/${clubId}`;

      // For create mode, ensure facilityId is provided
      if (mode === 'create' && !data.facilityId) {
        showErrorToast({ message: 'Please select a facility' });
        return;
      }

      // Build request body
      const body: Record<string, string | undefined> = {
        name: data.name,
      };

      // Only include slug if provided (API will auto-generate if empty)
      if (data.slug) {
        body.slug = data.slug;
      }

      // Only include facilityId for create mode
      if (mode === 'create') {
        body.facilityId = data.facilityId;
      }

      const res = await fetch(url, {
        method: mode === 'create' ? 'POST' : 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.error || 'Failed to save club');
      }

      showSuccessToast(
        mode === 'create'
          ? 'Club created successfully'
          : 'Club updated successfully'
      );

      router.push('/admin/clubs');
      router.refresh();
    } catch (error) {
      showErrorToast({
        message: error instanceof Error ? error.message : 'Failed to save club',
        retry: () => handleSubmit(onSubmit)(),
      });
    }
  };

  const inputClassName = "mt-1 block w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-1)] px-3 py-2 text-[var(--text-primary)] placeholder-[var(--text-muted)] shadow-sm focus:border-teal-500 focus:outline-none focus:ring-1 focus:ring-teal-500";

  return (
    <div className="rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-1)] p-6">
      <div className="mb-6">
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">
          {mode === 'create' ? 'Club Details' : 'Edit Club'}
        </h2>
        <p className="text-sm text-[var(--text-muted)] mt-1">
          {mode === 'create'
            ? 'Enter the details for the new club.'
            : 'Update club information.'}
        </p>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        {/* Basic Info Section */}
        <div className="space-y-4">
          <h3 className="text-sm font-medium text-[var(--text-secondary)] uppercase tracking-wide">
            Basic Information
          </h3>

          {/* Name */}
          <FormField
            label="Name"
            htmlFor="name"
            error={errors.name}
            required
          >
            <Input
              id="name"
              {...register('name')}
              onBlur={(e) => {
                register('name').onBlur(e);
                handleNameBlur();
              }}
              aria-invalid={errors.name ? 'true' : 'false'}
              className={inputClassName}
              placeholder="Riverside Rowing Club"
            />
          </FormField>

          {/* Slug */}
          <FormField
            label="URL Slug"
            htmlFor="slug"
            error={errors.slug}
            hint={mode === 'create' ? 'Auto-generated from name if left empty. Used in URLs.' : 'Used in club URLs.'}
          >
            <Input
              id="slug"
              {...register('slug', {
                onChange: handleSlugChange,
              })}
              aria-invalid={errors.slug ? 'true' : 'false'}
              className={inputClassName}
              placeholder="riverside-rowing-club"
            />
          </FormField>
        </div>

        {/* Facility Section */}
        <div className="space-y-4 pt-4 border-t border-[var(--border-subtle)]">
          <h3 className="text-sm font-medium text-[var(--text-secondary)] uppercase tracking-wide">
            Facility
          </h3>

          {mode === 'create' ? (
            <FormField
              label="Facility"
              htmlFor="facilityId"
              error={errors.facilityId}
              required
              hint="Select the facility this club belongs to."
            >
              <Controller
                name="facilityId"
                control={control}
                rules={{ required: 'Facility is required' }}
                render={({ field }) => (
                  <Select
                    value={field.value}
                    onValueChange={field.onChange}
                  >
                    <SelectTrigger className="w-full mt-1">
                      <SelectValue placeholder="Select a facility..." />
                    </SelectTrigger>
                    <SelectContent>
                      {facilities.map((facility) => (
                        <SelectItem key={facility.id} value={facility.id}>
                          {facility.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              />
            </FormField>
          ) : (
            <div className="space-y-1">
              <label className="block text-sm font-medium text-zinc-200">
                Facility
              </label>
              <div className="flex items-center gap-3 mt-1">
                <span className="px-3 py-2 bg-[var(--surface-2)] rounded-lg text-[var(--text-primary)] border border-[var(--border-subtle)]">
                  {currentFacilityName || 'Unknown'}
                </span>
                <span className="text-xs text-[var(--text-muted)]">
                  Use &quot;Move Club&quot; action in Danger Zone to change facility
                </span>
              </div>
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="flex gap-2 pt-4 border-t border-[var(--border-subtle)]">
          <Button type="submit" loading={isSubmitting}>
            {mode === 'create' ? 'Create Club' : 'Save Changes'}
          </Button>
          <Button
            type="button"
            variant="outline"
            onClick={() => router.back()}
          >
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}
